volumes:
  node_modules:
  vscode_extensions:
  vscode_insiders_extensions:

services:
  tests: &base
    build: &base-build
      context: .
      target: testing
      dockerfile: Dockerfile
      args:
        DEVELOPER_UID: ${UID:-1000}
        DEVELOPER_USER: ${USER:-you}
        NODE_CODENAME: ${NODE_CODENAME:-iron}
        DEBIAN_CODENAME: ${DEBIAN_CODENAME:-bookworm}
    image: vovimayhem/common-build-variables${TESTING_IMAGE_TAG:-:testing}
    
    working_dir: /workspaces/common-build-variables
    
    volumes:
      - .:/workspaces/common-build-variables
      - node_modules:/workspaces/common-build-variables/node_modules

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true

    # The command we want to execute by default when running the container
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined

    command: yarn test
    
  lib:
    <<: *base
    image: vovimayhem/common-build-variables:development
    build:
      <<: *base-build
      target: development
    entrypoint: /workspaces/common-build-variables/bin/dev-entrypoint
    volumes:
      - .:/workspaces/common-build-variables
      - node_modules:/workspaces/common-build-variables/node_modules
      - vscode_extensions:/home/${USER:-you}/.vscode-server/extensions
      - vscode_insiders_extensions:/home/${USER:-you}/.vscode-server-insiders/extensions

    command: vscode-wait # Éste comando está definido en `bin/dev-entrypoint`

    environment:
      GIT_EDITOR: code